### ISSUE TITLE
Pouvoir taper un mot de passe comportant des lettres

### ISSUE THREAD

**Issue by arthurzenika** [patou/biblionantes#4]
Comme recommandé lors de la creation d'un compte à la bibliothèque, j'ai changé mon mot de passe de ma date de naissance à un truc avec des lettres et des chiffres. Malheureusement le clavier proposé dans l'application pour le champs mot de passe ne comporte que des chiffres...

**Comment by patou** [comment]
Ha ok, moi je suis resté sur la date de naissance.
Je modifie ça.
